import { tx } from './tx';
import { useState } from 'react';
import { Link, NavLink, Navigate, Route, Routes, useLocation } from 'react-router-dom';
import { useQuery } from '@tanstack/react-query';
import { useTranslation } from 'react-i18next';
import { LayoutDashboard, ShieldCheck, ChartNoAxesCombined, Settings2, Search, Sparkles, CircleHelp, ArrowUpRight, ArrowRight, ChevronDown, SlidersHorizontal, Truck, Package, Clock3, RefreshCw, Menu, X, LogOut, Bell, CircleCheck } from 'lucide-react';
import { cases, demoMode, type Role } from './api/client';
import type { Case } from './api/types.generated';
import { source, referenceId } from './api/demo';
import { useRealtime } from './api/realtime';
import { Brand, Source, Status, Empty, Help, Chat, Heading } from './components';
import { Workspace, Approvals, Metrics, Admin } from './pages';
import { logout } from './auth';

export function App({ roles }: { roles: Role[] }) {
  const { t, i18n } = useTranslation();
  const location = useLocation();
  const [role, setRole] = useState<Role>(roles[0]);
  const [search, setSearch] = useState('');
  const [menu, setMenu] = useState(false);
  const [help, setHelp] = useState(false);
  const [chat, setChat] = useState(false);
  const [notifications, setNotifications] = useState(false);
  const [decision, setDecision] = useState<'APPROVED' | 'REJECTED' | null>(null);
  const realtimeCase = /^\/(?:cases|approvals)\/([^/]+)/.exec(location.pathname)?.[1];
  const connected = useRealtime(realtimeCase);
  const query = useQuery({ queryKey: ['cases'], queryFn: ({ signal }) => cases(signal), refetchInterval: demoMode || connected && !realtimeCase ? false : 2000 });
  const rows = (query.data ?? []).map(row => row.caseId === referenceId && decision ? { ...row, status: decision, stage: 'EXECUTE' as const } : row);
  const pathCase = realtimeCase ?? referenceId;
  const canApprove = role === 'approver';
  return <div className="app"><a className="skip-link" href="#content">{tx("Skip to content")}</a><header className="topbar"><button className="mobile-only icon-button" aria-label={tx("Toggle navigation")} onClick={() => setMenu(!menu)}>{menu ? <X/> : <Menu/>}</button><Link to="/board" aria-label={tx("AERA home")}><Brand/></Link><span className="top-divider"/><span className="workspace-name">{tx("Meridian Motors")} <ChevronDown size={13}/></span><div className="top-search"><Search size={17}/><input aria-label={tx("Search cases")} placeholder={t('search')} value={search} onChange={e => setSearch(e.target.value)}/><span>{tx("⌕")}</span></div><div className="top-actions"><button className="language" aria-label={tx("Change language")} onClick={() => { void i18n.changeLanguage(i18n.language === 'en' ? 'id' : 'en'); }}>{i18n.language.toUpperCase()}</button><button className="icon-button notification-button" aria-label={tx("Notifications")} onClick={() => setNotifications(!notifications)}><Bell size={19}/><i/></button><div className="avatar">{demoMode ? 'MP' : role.charAt(0).toUpperCase()}</div><div className="profile"><strong>{demoMode ? tx("Meridian planner") : tx("Your workspace")}</strong>{demoMode ? <select aria-label={tx("Demo role")} value={role} onChange={e => setRole(e.target.value as Role)}>{roles.map(r => <option key={r} value={r}>{tx(r)}</option>)}</select> : <span>{tx(role)}</span>}</div>{!demoMode && <button aria-label={tx("Sign out")} className="icon-button" onClick={() => { void logout(); }}><LogOut size={17}/></button>}</div></header>
    <aside className={`sidebar ${menu ? 'open' : ''}`}><div className="sidebar-label">{tx("WORKSPACE")}</div><nav aria-label={tx("Main navigation")}>{[[LayoutDashboard, 'board', '/board'], [ShieldCheck, 'approvals', '/approvals'], [ChartNoAxesCombined, 'metrics', '/metrics'], [Settings2, 'admin', '/admin']].map(([Icon, label, url]) => { const NavIcon = Icon as typeof LayoutDashboard; return <NavLink key={String(url)} to={String(url)} onClick={() => setMenu(false)} className={({ isActive }) => isActive ? 'nav-item active' : 'nav-item'}><NavIcon size={19}/>{t(String(label))}{label === 'approvals' && demoMode && !decision && <span className="nav-count">{tx("1")}</span>}</NavLink>; })}</nav><div className="sidebar-note"><div className="tiny-star">{tx("✦")}</div><strong>{tx("A little help.")}<br/>{tx("A clearer next step.")}</strong><p>{tx("Make sense of an exception, together.")}</p><button onClick={() => setChat(true)}>{t('ask')}<ArrowUpRight size={15}/></button></div><div className="sidebar-bottom"><button onClick={() => setHelp(true)}><CircleHelp size={18}/> {tx("Help & getting started")}</button><div className="connection"><span className={demoMode ? 'demo-dot' : connected ? 'live-dot' : 'demo-dot'}/>{demoMode ? tx("Synthetic demo · no live writes") : connected ? tx("Live updates connected") : tx("Polling for updates")}</div><span className="version-label">{tx("AERA / A clearer way forward")}</span></div></aside>
    <main id="content" className="main" tabIndex={-1}><div className="environment"><span className="environment-label"><i/>{demoMode ? t('demo') : 'Connected workspace'}</span><span>{demoMode ? tx("Reference scenario · synthetic data") : tx("SAP-backed operations")}</span></div>{notifications && <div className="notification-panel"><strong>{tx("Your updates")}</strong><p>{demoMode && !decision ? tx("The brake caliper case is ready for an approval review.") : tx("You’re up to date.")}</p><Link to="/approvals" onClick={() => setNotifications(false)}>{tx("Open approvals")} <ArrowRight size={14}/></Link></div>}
      {query.isPending ? <div className="loading" role="status"><RefreshCw className="spin"/> {tx("Preparing your workspace…")}</div> : query.isError ? <Empty title={tx("We couldn’t load your workspace")}><span role="alert">{query.error.message}</span><br/><button className="secondary" onClick={() => { void query.refetch(); }}>{tx("Try again")}</button></Empty> : <Routes><Route path="/" element={<Navigate to="/board" replace/>}/><Route path="/callback" element={<Navigate to="/board" replace/>}/><Route path="/board" element={<Board rows={rows} search={search} ask={() => setChat(true)}/>}/><Route path="/cases/:id/:stage" element={<Workspace rows={rows} role={role} decision={decision} decide={setDecision} ask={() => setChat(true)} connected={connected}/>}/><Route path="/approvals" element={<Approvals rows={rows} canApprove={canApprove}/>}/><Route path="/approvals/:id" element={<Workspace rows={rows} role={role} decision={decision} decide={setDecision} ask={() => setChat(true)} connected={connected} approvalOnly/>}/><Route path="/metrics" element={<Metrics rows={rows}/>}/><Route path="/admin" element={<Admin role={role}/>}/><Route path="*" element={<Empty title={tx("This page isn’t here")}><Link to="/board">{tx("Return to the case board")}</Link></Empty>}/></Routes>}
      <footer className="footer"><span>{tx("AERA · Autonomous Exception Resolution Agent")}</span><span>{tx("Problems move supply chains. AERA resolves them.")}</span></footer>
    </main><Help open={help} close={() => setHelp(false)}/>{chat && <Chat caseId={pathCase} close={() => setChat(false)}/>}</div>;
}

function Board({ rows, search, ask }: { rows: Case[]; search: string; ask: () => void }) {
  const { t } = useTranslation();
  const [type, setType] = useState('all');
  const [tier, setTier] = useState('all');
  const [tab, setTab] = useState('all');
  const [filters, setFilters] = useState(false);
  const [sort, setSort] = useState('priority');
  const filtered = rows.filter(row => `${row.caseId} ${row.material} ${row.materialDescription} ${row.poNumber ?? ''}`.toLowerCase().includes(search.toLowerCase()) && (type === 'all' || row.type === type) && (tier === 'all' || String(row.tier) === tier) && (tab === 'all' || tab === 'approval' && row.status === 'AWAITING_APPROVAL' || tab === 'new' && row.status === 'RECEIVED')).sort((a, b) => sort === 'priority' ? (b.priorityScore ?? -1) - (a.priorityScore ?? -1) : a.caseId.localeCompare(b.caseId));
  const ref = rows.find(r => r.caseId === referenceId);
  return <><div className="overview-kicker"><span>{tx("YOUR OPERATIONS, IN FOCUS")}</span><span className="muted">{demoMode ? tx("Reference day · 14 September") : tx("Operations overview")}</span></div><section className="hero"><div className="hero-copy"><span className="hero-eyebrow"><Sparkles size={15}/> {tx("A clearer way forward")}</span><h1>{t('title')}</h1><p>{tx("Turn supply chain surprises into confident next steps.")}<br/>{t('subtitle')}</p><div className="hero-buttons"><Link className="primary" to={ref ? `/cases/${ref.caseId}/impact` : '/approvals'}>{t('view')}<ArrowUpRight size={17}/></Link><button className="text-button" onClick={ask}>{tx("Explore with AERA")} <ArrowRight size={16}/></button></div></div><div className="hero-art" aria-hidden="true"><div className="orbit orbit-one"/><div className="orbit orbit-two"/><div className="float-symbol package"><Package size={23}/></div><div className="float-symbol truck"><Truck size={23}/></div><img src="/brand/mascot.png" alt=""/><div className="mascot-note"><span className="check-circle"><CircleCheck size={13}/></span>{tx("Every exception. A way forward.")}</div></div></section>
      <div className="stat-grid"><Stat label={tx("Revenue at risk")} value={demoMode ? '$4.72M' : '—'} note={tx("Reference case exposure")} sourceRef={source.demand} tone="blue" icon={<ChartNoAxesCombined/>}/><Stat label={tx("Needs your attention")} value={String(rows.filter(r => r.status === 'AWAITING_APPROVAL').length)} note={tx("Awaiting an approval decision")} sourceRef="console:cases/status=AWAITING_APPROVAL" tone="violet" icon={<ShieldCheck/>}/><Stat label={tx("Time to stock-out")} value={demoMode ? '6h 12m' : '—'} note={tx("Cikarang · brake caliper housing")} sourceRef={source.stock} tone="amber" icon={<Clock3/>}/><Stat label={tx("Signals, made simpler")} value={demoMode ? '214 → 6' : '—'} note={tx("Messages to actionable exceptions")} sourceRef={source.seed} tone="cyan" icon={<Sparkles/>}/></div>
      <section className="case-section"><Heading eyebrow={tx("EXCEPTION WORKSPACE")} title={t('cases')}><button className="secondary compact" onClick={() => setFilters(!filters)} aria-expanded={filters}><SlidersHorizontal size={15}/> {tx("Filters")}{(type !== 'all' || tier !== 'all') && <i className="filter-dot"/>}</button></Heading><div className="table-toolbar"><div className="tabs">{[['all', t('all')], ['approval', tx("Needs approval")], ['new', tx("New signals")]].map(([id, label]) => <button key={id} className={tab === id ? 'selected' : ''} onClick={() => setTab(id)}>{label}{id === 'all' && <Source sourceRef="console:cases/count"><span className="count">{rows.length}</span></Source>}</button>)}</div><label className="sort">{tx("Sort by")} <select aria-label={tx("Sort cases")} value={sort} onChange={e => setSort(e.target.value)}><option value="priority">{tx("Priority")}</option><option value="id">{tx("Case ID")}</option></select></label></div>{filters && <div className="filter-panel"><label>{tx("Exception type")}<select aria-label={tx("Exception type")} value={type} onChange={e => setType(e.target.value)}><option value="all">{tx("All types")}</option><option value="SUPPLIER_DELAY">{tx("Supplier delay")}</option><option value="QUANTITY_SHORTFALL">{tx("Material shortage")}</option><option value="CARRIER_DELAY">{tx("Carrier delay")}</option></select></label><label>{tx("Autonomy tier")}<select aria-label={tx("Autonomy tier")} value={tier} onChange={e => setTier(e.target.value)}><option value="all">{tx("All tiers")}</option><option value="1">{tx("Tier 1 · Auto")}</option><option value="2">{tx("Tier 2 · Approval")}</option><option value="3">{tx("Tier 3 · Escalate")}</option></select></label><button className="text-button" onClick={() => { setType('all'); setTier('all'); }}>{tx("Clear filters")}</button></div>}
      <div className="table-scroll"><table className="case-table"><thead><tr><th>{tx("Exception / material")}</th><th>{tx("Plant")}</th><th>{tx("Revenue at risk")}</th><th>{tx("Status")}</th><th aria-label={tx("Open case")}/></tr></thead><tbody>{filtered.map((row, i) => <tr key={row.caseId}><td><div className="case-cell"><span className={`case-icon ${i === 0 ? 'blue' : i === 1 ? 'violet' : 'cyan'}`}>{row.type === 'CARRIER_DELAY' ? <Truck size={19}/> : <Package size={19}/>}</span><div><Link className="case-title" to={`/cases/${row.caseId}/${row.stage.toLowerCase()}`}>{row.materialDescription ?? row.material}<ArrowUpRight size={13}/></Link><div className="case-sub"><Source sourceRef={demoMode ? source.seed : `case:${row.caseId}`}>{row.caseId} {tx("·")} {row.material}</Source></div></div></div></td><td><Source sourceRef={demoMode ? source.po : `case:${row.caseId}/plant`}>{row.plant}</Source><span className="cell-sub">{demoMode ? row.plant === '1010' ? 'Cikarang' : 'Karawang' : ''}</span></td><td>{row.rarUsd != null ? <Source sourceRef={row.figures?.find(f => f.name === 'Revenue at risk')?.sourceRef ?? `case:${row.caseId}/rarUsd`}>{tx("$")}{(row.rarUsd / 1000000).toFixed(2)}{tx("M")}</Source> : <span className="muted">{tx("Awaiting analysis")}</span>}</td><td><Status value={row.status}/>{row.tier && <span className="cell-sub">{tx("Tier")} {row.tier} {tx("· Human review")}</span>}</td><td><Link className="row-link" aria-label={`Open ${row.caseId}`} to={`/cases/${row.caseId}/${row.stage.toLowerCase()}`}><ArrowRight size={18}/></Link></td></tr>)}</tbody></table>{!filtered.length && <Empty title={tx("No matching cases")}>{tx("Try another search or clear your filters.")}</Empty>}</div><div className="table-bottom"><span><Source sourceRef="console:filtered-cases/count">{filtered.length}</Source> {tx("cases in this view")}</span><span className="inline"><ShieldCheck size={13}/>{demoMode ? tx("Synthetic reference scenario") : tx("Source-linked operational data")}</span></div></section>
      <div className="bottom-grid"><div className="calm-card"><span className="card-symbol"><ShieldCheck size={20}/></span><div><h3>{tx("Confidence comes from evidence.")}</h3><p>{tx("Every figure has a source. Every action follows your rules.")}</p></div><button aria-label={tx("Learn about source evidence")} onClick={ask}><ArrowUpRight size={20}/></button></div><div className="calm-card"><span className="card-symbol cyan"><Sparkles size={20}/></span><div><h3>{tx("You stay in control.")}</h3><p>{tx("AERA investigates. You approve the decisions that matter.")}</p></div></div></div></>;
}
function Stat({ label, value, note, sourceRef, tone, icon }: { label: string; value: string; note: string; sourceRef: string; tone: string; icon: React.ReactNode }) { return <div className={`stat ${tone}`}><div className="stat-top"><span>{label}</span><span className="stat-icon">{icon}</span></div><div className="stat-value"><Source sourceRef={sourceRef}>{value}</Source></div><div className="stat-note">{note}</div></div>; }
