import i18n from 'i18next';
import { initReactI18next } from 'react-i18next';
import { idCopy } from './id-copy';
void i18n.use(initReactI18next).init({ lng: 'en', fallbackLng: 'en', keySeparator: false, interpolation: { escapeValue: false }, resources: {
  en: { translation: { board: 'Overview', approvals: 'Approvals', metrics: 'Insights', admin: 'Settings', title: 'A little clarity. A lot of progress.', subtitle: 'Your supply chain, moving forward.', search: 'Search cases, materials or purchase orders', cases: 'Your attention makes the difference.', all: 'All cases', demo: 'Demo workspace', view: 'Review priority case', ask: 'Ask AERA', signal: 'Signal', triage: 'Triage', impact: 'Impact', options: 'Options', approve: 'Approve', execute: 'Execute', dialogueThread: 'Supplier dialogue', dialogueUnavailable: 'Dialogue unavailable. Retrying.', loadingDialogue: 'Loading dialogue...', noDialogue: 'No supplier questions for this case.', language: 'Language', oneReminderSent: 'One reminder sent', supplierReply: 'Supplier reply', untrustedSupplierText: 'Supplier content is untrusted evidence.', CONFIRM_PARTIAL_QTY: 'Confirm partial quantity', CONFIRM_SHIP_DATE: 'Confirm shipping date', REQUEST_TRACKING: 'Request tracking', DRAFT: 'Draft', SENT: 'Sent', REPLIED: 'Replied', TIMED_OUT: 'Timed out', BLOCKED: 'Blocked', originalMessage: 'Original', englishCopy: 'English copy' } },
  id: { translation: { board: 'Ringkasan', approvals: 'Persetujuan', metrics: 'Wawasan', admin: 'Pengaturan', title: 'Lebih jelas. Lebih banyak kemajuan.', subtitle: 'Rantai pasok Anda, terus bergerak.', search: 'Cari kasus, material, atau pesanan', cases: 'Perhatian Anda membuat perbedaan.', all: 'Semua kasus', demo: 'Ruang kerja demo', view: 'Tinjau kasus prioritas', ask: 'Tanya AERA', signal: 'Sinyal', triage: 'Triase', impact: 'Dampak', options: 'Opsi', approve: 'Setujui', execute: 'Eksekusi', dialogueThread: 'Percakapan pemasok', dialogueUnavailable: 'Percakapan tidak tersedia. Mencoba lagi.', loadingDialogue: 'Memuat percakapan...', noDialogue: 'Belum ada pertanyaan untuk pemasok.', language: 'Bahasa', oneReminderSent: 'Satu pengingat telah dikirim', supplierReply: 'Balasan pemasok', untrustedSupplierText: 'Isi pesan pemasok adalah bukti yang belum tepercaya.', CONFIRM_PARTIAL_QTY: 'Konfirmasi jumlah sebagian', CONFIRM_SHIP_DATE: 'Konfirmasi tanggal pengiriman', REQUEST_TRACKING: 'Minta nomor pelacakan', DRAFT: 'Draf', SENT: 'Terkirim', REPLIED: 'Dibalas', TIMED_OUT: 'Waktu habis', BLOCKED: 'Diblokir', originalMessage: 'Asli', englishCopy: 'Salinan bahasa Inggris' } },
} });
i18n.addResourceBundle('id', 'translation', idCopy, true, true);
export default i18n;
