// Indonesian copy for the existing console. Keys match visible English text.
export const idCopy: Record<string, string> = {
  '. A planner must confirm this field before it can be used.': '. Perencana harus mengonfirmasi kolom ini sebelum digunakan.',
  '. No real SAP action was performed.': '. Tidak ada tindakan SAP nyata yang dilakukan.',
  '. This action is irreversible in a live workspace.': '. Tindakan ini tidak dapat dibatalkan dalam ruang kerja aktif.',
  '1,550 units': '1.550 unit', '10 sales orders': '10 pesanan penjualan',
  '30 days': '30 hari', '310 units': '310 unit', '72 hours': '72 jam',
  'AERA / A clearer way forward': 'AERA / Langkah ke depan yang lebih jelas',
  'AERA home': 'Beranda AERA',
  'AERA \u00b7 Autonomous Exception Resolution Agent': 'AERA \u00b7 Agen Penyelesaian Pengecualian Otonom',
  'Air freight A': 'Pengiriman udara A', 'Air freight \u00b7 irreversible': 'Pengiriman udara \u00b7 tidak dapat dibatalkan',
  'Amount:': 'Jumlah:', 'Ask AERA': 'Tanya AERA',
  'Ask a question about this case\u2026': 'Ajukan pertanyaan tentang kasus ini...',
  'Cikarang \u00b7 brake caliper housing': 'Cikarang \u00b7 rumah kaliper rem',
  'Cikarang \u00b7 plant 1010': 'Cikarang \u00b7 pabrik 1010',
  'Irreversible \u00b7 air-freight booking': 'Tidak dapat dibatalkan \u00b7 pemesanan pengiriman udara',
  'Krieger Guss GmbH \u00b7 synthetic supplier message': 'Krieger Guss GmbH \u00b7 pesan pemasok sintetis',
  'Line 2 \u00b7 reference window': 'Lini 2 \u00b7 periode acuan',
  'SAP Mirror \u00b7 demo': 'SAP Mirror \u00b7 demo',
  'Tier 1 \u00b7 Auto': 'Tingkat 1 \u00b7 otomatis',
  'Tier 2': 'Tingkat 2', 'Tier 2 \u00b7 Approval': 'Tingkat 2 \u00b7 persetujuan',
  'Tier 3 \u00b7 Escalate': 'Tingkat 3 \u00b7 eskalasi',
  'Transfer C': 'Transfer C', 'remains unchanged.': 'tetap sama.',
  'units': 'unit', '\u00b7 Human review': '\u00b7 tinjauan manusia',
  'A clear view of the work in front of you. Results appear when they are measured.': 'Gambaran pekerjaan saat ini. Hasil muncul setelah diukur.',
  'A clearer next step.': 'Langkah berikutnya lebih jelas.',
  'A clearer path from signal to resolution': 'Alur yang jelas dari sinyal hingga penyelesaian',
  'A clearer way forward': 'Langkah ke depan yang lebih jelas',
  'A little help.': 'Sedikit bantuan.',
  'A look-alike sender was quarantined': 'Pengirim yang menyerupai alamat asli dikarantina',
  'A readable trail of evidence and decisions.': 'Jejak bukti dan keputusan yang mudah dibaca.',
  'A small part. A significant impact.': 'Komponen kecil. Dampak besar.',
  'A transfer from Karawang can arrive before the line runs out of stock.': 'Transfer dari Karawang dapat tiba sebelum stok lini habis.',
  'Administered rate-card and approver-limit editing awaits the corresponding live API.': 'Perubahan tarif dan batas persetujuan menunggu API aktif.',
  'Administrator access required': 'Perlu akses administrator',
  'Advise-only mode': 'Mode saran saja',
  'AERA investigates. You approve the decisions that matter.': 'AERA menyelidiki. Anda menyetujui keputusan penting.',
  'AERA proposes. Your governance rules decide.': 'AERA mengusulkan. Aturan tata kelola Anda menentukan.',
  'Air freight is irreversible and requires a named approver. The reversible transfer is handled separately under the urgent partial-execution rule.': 'Pengiriman udara tidak dapat dibatalkan dan memerlukan penyetuju yang ditunjuk. Transfer yang dapat dibatalkan ditangani terpisah menurut aturan eksekusi sebagian yang mendesak.',
  'All tiers': 'Semua tingkat', 'All types': 'Semua jenis',
  'Approval amount': 'Jumlah persetujuan', 'Approval comment': 'Komentar persetujuan',
  'Arrival': 'Kedatangan', 'Autonomy thresholds': 'Ambang otonomi',
  'Autonomy tier': 'Tingkat otonomi', 'Available stock': 'Stok tersedia',
  'Awaiting an approval decision': 'Menunggu keputusan persetujuan',
  'Awaiting analysis': 'Menunggu analisis', 'Awaiting approval': 'Menunggu persetujuan',
  'Baseline': 'Kondisi awal',
  'Bridge the immediate gap, then cover the remaining demand.': 'Atasi kekurangan segera, lalu penuhi sisa permintaan.',
  'Calculating projection...': 'Menghitung proyeksi...', 'Cancel': 'Batal',
  'Carrier delay': 'Keterlambatan pengangkut', 'Case / plan part': 'Kasus / bagian rencana',
  'Case ID': 'ID kasus', 'Case or stage not found': 'Kasus atau tahap tidak ditemukan',
  'Case stages': 'Tahap kasus', 'Case trajectory': 'Jejak kasus',
  'cases in this view': 'kasus dalam tampilan ini', 'Change language': 'Ganti bahasa',
  'Change quantity or donor plant. This recalculates checks and projection; plan of record stays intact.': 'Ubah jumlah atau pabrik asal. Pemeriksaan dan proyeksi dihitung ulang; rencana resmi tetap sama.',
  'Check the original evidence, then enter the confirmed quantity. In this demo your confirmation changes only the field display, not the proposed plan.': 'Periksa bukti asli, lalu masukkan jumlah yang dipastikan. Dalam demo, konfirmasi hanya mengubah tampilan kolom, bukan rencana.',
  'Checks': 'Pemeriksaan', 'Chosen plan': 'Rencana terpilih',
  'Clear filters': 'Hapus filter', 'Closed cases': 'Kasus selesai',
  'Compare current path with a proposed recovery. Shaded periods mark line stops.': 'Bandingkan kondisi saat ini dengan usulan pemulihan. Area berarsir menandai berhentinya lini.',
  'Compare the proposed options, their sources and the checks that matter.': 'Bandingkan opsi, sumber data, dan pemeriksaan penting.',
  'Confidence comes from evidence.': 'Keyakinan berasal dari bukti.',
  'Confirm extracted quantity': 'Pastikan jumlah yang diekstrak',
  'Confirm field': 'Konfirmasi kolom', 'Confirm reset': 'Konfirmasi pengaturan ulang',
  'Confirmed quantity': 'Jumlah terkonfirmasi', 'Cost': 'Biaya',
  'Coverage': 'Cakupan', 'Customer commitments': 'Komitmen pelanggan',
  'Deadline': 'Batas waktu', 'Dealer and fleet customers': 'Pelanggan dealer dan armada',
  'Decisions that need a person, with the evidence ready to review.': 'Keputusan yang memerlukan manusia, dengan bukti siap ditinjau.',
  'Default configuration from the specification. Live changes must be audited by the server.': 'Konfigurasi bawaan dari spesifikasi. Perubahan aktif harus diaudit oleh server.',
  'Delivery update \u00b7 brake caliper housing': 'Pembaruan pengiriman \u00b7 rumah kaliper rem',
  'Demo approver limit': 'Batas penyetuju demo', 'Demo plan': 'Rencana demo',
  'Demo role': 'Peran demo', 'Dismiss notification': 'Tutup pemberitahuan',
  'Donor plant': 'Pabrik asal', 'Email and photo \u00b7 demo evidence': 'Email dan foto \u00b7 bukti demo',
  'Every exception. A way forward.': 'Setiap pengecualian punya jalan keluar.',
  'Every figure has a source. Every action follows your rules.': 'Setiap angka punya sumber. Setiap tindakan mengikuti aturan Anda.',
  'Evidence first. Every step.': 'Bukti di setiap langkah.',
  'Exception / material': 'Pengecualian / material', 'Exception type': 'Jenis pengecualian',
  'EXCEPTION WORKSPACE': 'RUANG KERJA PENGECUALIAN',
  'Execution is controlled by the deterministic workflow, with undo recorded before writes.': 'Eksekusi dikendalikan alur kerja deterministik; rencana pembatalan dicatat sebelum penulisan.',
  'Expedite the ready partial shipment': 'Percepat pengiriman sebagian yang siap',
  'Explore resolution options': 'Jelajahi opsi penyelesaian',
  'Explore with AERA': 'Jelajahi bersama AERA', 'Extracted fields': 'Kolom hasil ekstraksi',
  'Extraction confidence:': 'Tingkat keyakinan ekstraksi:', 'Filters': 'Filter',
  'First stock-out': 'Stok pertama kali habis', 'Follow every step forward.': 'Ikuti setiap langkah.',
  'From stock to customer commitments': 'Dari stok hingga komitmen pelanggan',
  'Got it': 'Mengerti',
  'Guardrails for how AERA operates across your workspace.': 'Aturan pengaman untuk operasi AERA di ruang kerja Anda.',
  'Help & getting started': 'Bantuan dan panduan awal',
  'Hover or focus a dotted-underlined figure to see its source. On a phone, tap the figure.': 'Arahkan atau fokus pada angka bergaris bawah titik untuk melihat sumbernya. Di ponsel, ketuk angka.',
  'HUMAN IN THE LOOP': 'KEPUTUSAN MANUSIA',
  'I reviewed the plan, its cost and the irreversible action. I understand this is a local demo decision.': 'Saya telah meninjau rencana, biaya, dan tindakan yang tidak dapat dibatalkan. Saya memahami ini hanya keputusan demo lokal.',
  'In the demo workspace, all data is synthetic and actions stay in this browser. Change the demo role in the header to explore approval and administration.': 'Dalam ruang kerja demo, semua data bersifat sintetis dan tindakan hanya terjadi di peramban ini. Ganti peran demo di bagian atas untuk melihat persetujuan dan administrasi.',
  'It started with a supplier update.': 'Semua bermula dari pembaruan pemasok.',
  'Learn about source evidence': 'Pelajari sumber bukti',
  'Line stop': 'Lini berhenti', 'Line-stop windows': 'Periode lini berhenti',
  'Live deadline unavailable in demo': 'Batas waktu aktif tidak tersedia dalam demo',
  'Live execution is controlled by the backend. Chat never grants approval.': 'Eksekusi aktif dikendalikan backend. Percakapan tidak memberikan persetujuan.',
  'Main navigation': 'Navigasi utama',
  'Make sense of an exception, together.': 'Pahami pengecualian bersama.',
  'Material shortage': 'Kekurangan material',
  'Measured outcomes, coming with live runs': 'Hasil terukur akan tersedia setelah proses aktif',
  'Message AERA': 'Kirim pesan ke AERA', 'Messages to actionable exceptions': 'Pesan menjadi pengecualian yang dapat ditindaklanjuti',
  'Minimum confidence': 'Keyakinan minimum', 'More than one way forward.': 'Ada lebih dari satu jalan keluar.',
  'Needs your attention': 'Perlu perhatian Anda',
  'No cases are waiting for approval in this workspace.': 'Tidak ada kasus yang menunggu persetujuan.',
  'No executed action exists to roll back': 'Tidak ada tindakan tereksekusi yang dapat dibatalkan',
  'No matching cases': 'Tidak ada kasus yang cocok', 'No trajectory events yet.': 'Belum ada peristiwa dalam jejak kasus.',
  'Not started': 'Belum dimulai', 'Notifications': 'Pemberitahuan',
  'Open approvals': 'Buka persetujuan', 'Open case': 'Buka kasus',
  'OPERATIONAL INSIGHTS': 'WAWASAN OPERASIONAL',
  'Option': 'Opsi', 'Orders affected': 'Pesanan terdampak', 'Plant': 'Pabrik',
  'Preparing your workspace\u2026': 'Menyiapkan ruang kerja Anda...',
  'Priority': 'Prioritas', 'Priority breakdown': 'Rincian prioritas',
  'Priority is based on source-backed revenue exposure and urgency.': 'Prioritas dihitung dari risiko pendapatan dan urgensi yang bersumber jelas.',
  'Priority is calculated by the rules service, not assigned by a model.': 'Prioritas dihitung oleh layanan aturan, bukan ditentukan model.',
  'Priority score': 'Skor prioritas',
  'Problems move supply chains. AERA resolves them.': 'Gangguan mengubah rantai pasok. AERA menanganinya.',
  'Production demand': 'Permintaan produksi', 'Progress you can trace.': 'Kemajuan yang dapat ditelusuri.',
  'Projection option': 'Opsi proyeksi', 'Projection plant': 'Pabrik proyeksi',
  'Projection range': 'Rentang proyeksi', 'Projection sources:': 'Sumber proyeksi:',
  'Proposed plan \u00b7 explicit approval required': 'Rencana usulan \u00b7 perlu persetujuan tegas',
  'Quantity': 'Jumlah', 'Ready partial quantity': 'Jumlah sebagian yang siap',
  'Recommended: transfer + air freight': 'Rekomendasi: transfer + pengiriman udara',
  'Reference case exposure': 'Paparan kasus acuan', 'Reference rate card': 'Daftar tarif acuan',
  'Reject plan': 'Tolak rencana', 'Reset demo settings': 'Atur ulang pengaturan demo',
  'Reset local demo settings?': 'Atur ulang pengaturan demo lokal?',
  'Reset local settings': 'Atur ulang pengaturan lokal',
  'Resolution time, model cost, human touches and revenue protected require completed backend runs. No performance uplift is claimed from demo data.': 'Waktu penyelesaian, biaya model, keterlibatan manusia, dan pendapatan terlindungi memerlukan proses backend yang selesai. Data demo bukan bukti peningkatan kinerja.',
  'Restore the default values displayed on this page. This does not reset SAP, case data or any environment.': 'Pulihkan nilai bawaan pada halaman ini. Tindakan ini tidak mengatur ulang SAP, data kasus, atau lingkungan.',
  'Restore the local demo defaults.': 'Pulihkan nilai bawaan demo lokal.',
  'Return to overview': 'Kembali ke ringkasan', 'Return to the case board': 'Kembali ke daftar kasus',
  'Revenue at risk': 'Pendapatan berisiko', 'Reversibility': 'Dapat dibatalkan',
  'Review & approve': 'Tinjau dan setujui', 'Review & confirm field': 'Tinjau dan konfirmasi kolom',
  'Review approval': 'Tinjau persetujuan', 'Review decision': 'Tinjau keputusan',
  'Review needed': 'Perlu ditinjau', 'Review required in the connected verifier': 'Perlu pemeriksaan pada verifier terhubung',
  'Review the original signals before acting on extracted information.': 'Tinjau sinyal asli sebelum menggunakan informasi hasil ekstraksi.',
  'Review the plan, source evidence and irreversible actions before confirming.': 'Tinjau rencana, sumber bukti, dan tindakan yang tidak dapat dibatalkan sebelum mengonfirmasi.',
  'Review the source evidence and proposed resolution before making a decision.': 'Tinjau sumber bukti dan usulan penyelesaian sebelum memutuskan.',
  'Roll back executed plan': 'Batalkan rencana yang dieksekusi', 'Run what-if': 'Jalankan simulasi',
  'Save demo settings': 'Simpan pengaturan demo', 'Search cases': 'Cari kasus',
  'Send message': 'Kirim pesan',
  'Sender domain did not match the supplier master. Its content cannot authorise an action.': 'Domain pengirim tidak cocok dengan data induk pemasok. Pesan ini tidak dapat mengizinkan tindakan.',
  'Sign out': 'Keluar', 'Signals, made simpler': 'Sinyal menjadi lebih sederhana',
  'Skip to content': 'Lewati ke konten', 'Sort by': 'Urutkan menurut',
  'Sort cases': 'Urutkan kasus', 'Sources:': 'Sumber:',
  'Start with the case board. Open a case and follow the six stages to inspect its signals, impact, options, approval and execution.': 'Mulai dari daftar kasus. Buka kasus dan ikuti enam tahap untuk memeriksa sinyal, dampak, opsi, persetujuan, dan eksekusi.',
  'Status': 'Status', 'Stock projection': 'Proyeksi stok',
  'Stock runs out in': 'Stok habis dalam', 'Stock through time': 'Perubahan stok dari waktu ke waktu',
  'Stop new execution. Keep the investigation and recommendations.': 'Hentikan eksekusi baru. Lanjutkan penyelidikan dan rekomendasi.',
  'Supplier delay': 'Keterlambatan pemasok', 'Supplier email': 'Email pemasok',
  'Synthetic projection only. Verifier checks require a connected workspace.': 'Proyeksi sintetis saja. Pemeriksaan verifier memerlukan ruang kerja terhubung.',
  'Synthetic SAP Mirror scenario': 'Skenario SAP Mirror sintetis',
  'The brake caliper shortage threatens the Cikarang production line.': 'Kekurangan rumah kaliper rem mengancam lini produksi Cikarang.',
  'The decision stays with you.': 'Keputusan tetap di tangan Anda.',
  'The right exception, first.': 'Tangani pengecualian yang tepat lebih dulu.',
  'The shipment is delayed. A partial quantity is ready to send by air; the remaining balance will follow by sea.': 'Pengiriman terlambat. Sebagian barang siap dikirim lewat udara; sisanya menyusul lewat laut.',
  'This page is available to the admin role.': 'Halaman ini tersedia untuk peran administrator.',
  'This page isn\u2019t here': 'Halaman ini tidak ditemukan',
  'This reference case reaches stock-out within one day. The deterministic priority rule uses the highest urgency multiplier.': 'Stok kasus acuan ini habis dalam satu hari. Aturan prioritas deterministik menggunakan pengali urgensi tertinggi.',
  'This screen demonstrates the approval interaction. Current plan hash, deadline and verifier results must be revalidated by the server in live mode.': 'Layar ini menunjukkan interaksi persetujuan. Hash rencana, batas waktu, dan hasil verifier harus divalidasi ulang oleh server dalam mode aktif.',
  'Tier': 'Tingkat', 'Tier 1 maximum': 'Batas maksimum Tingkat 1',
  'Tier 1 maximum (USD)': 'Batas maksimum Tingkat 1 (USD)',
  'Time to stock-out': 'Waktu hingga stok habis', 'Toggle navigation': 'Buka/tutup navigasi',
  'Trace unavailable. Retrying with polling.': 'Jejak tidak tersedia. Mencoba lagi lewat polling.',
  'Try again': 'Coba lagi', 'Try another search or clear your filters.': 'Coba pencarian lain atau hapus filter.',
  'Try another transfer': 'Coba transfer lain',
  'Turn supply chain surprises into confident next steps.': 'Ubah gangguan rantai pasok menjadi langkah yang pasti.',
  'Understand the impact. Choose the next step.': 'Pahami dampaknya. Pilih langkah berikutnya.',
  'Urgency multiplier': 'Pengali urgensi',
  'Use the demo role selector to switch to approver. Planner and admin roles cannot approve.': 'Gunakan pemilih peran demo untuk beralih menjadi penyetuju. Perencana dan administrator tidak dapat menyetujui.',
  'Vehicles at risk': 'Kendaraan berisiko', 'Visible cases': 'Kasus terlihat',
  'We couldn\u2019t load your workspace': 'Ruang kerja tidak dapat dimuat',
  'What-if donor plant': 'Pabrik asal simulasi', 'What-if only. Plan version': 'Hanya simulasi. Versi rencana',
  'What-if quantity': 'Jumlah simulasi', 'Where work stands': 'Posisi pekerjaan saat ini',
  'With option': 'Dengan opsi',
  'Workflow preview only. No live workflow or SAP document has been created.': 'Pratinjau alur kerja saja. Belum ada alur kerja aktif atau dokumen SAP yang dibuat.',
  'WORKSPACE': 'RUANG KERJA', 'WORKSPACE SETTINGS': 'PENGATURAN RUANG KERJA',
  'You are reviewing the air-freight plan for': 'Anda sedang meninjau rencana pengiriman udara untuk',
  'You can inspect the evidence.': 'Anda dapat memeriksa bukti.',
  'You stay in control.': 'Kendali tetap di tangan Anda.',
  'You\u2019re all caught up.': 'Semua pekerjaan sudah ditangani.',
  'Your judgement. The next step.': 'Penilaian Anda menentukan langkah berikutnya.',
  'YOUR OPERATIONS, IN FOCUS': 'FOKUS PADA OPERASI ANDA',
  'Your rules. Always in control.': 'Aturan Anda. Kendali tetap terjaga.',
  'Your updates': 'Pembaruan Anda',
  'planner': 'perencana', 'approver': 'penyetuju', 'admin': 'administrator',
  'Move stock from Karawang': 'Pindahkan stok dari Karawang',
  'Inter-plant transfer': 'Transfer antar pabrik',
  'Use available stock at plant 1020 to bridge the immediate shortage.': 'Gunakan stok di pabrik 1020 untuk menutup kekurangan segera.',
  'Expedite the ready shipment': 'Percepat pengiriman yang siap',
  'Air freight': 'Pengiriman udara',
  'Bring the ready partial shipment forward while the balance travels by sea.': 'Percepat pengiriman sebagian yang siap sementara sisanya dikirim lewat laut.',
  'Source from Halim Presisi': 'Pasok dari Halim Presisi',
  'Alternate supplier': 'Pemasok alternatif',
  'Supplier compliance is UNDER_REVIEW. This option is blocked by V-06.': 'Kepatuhan pemasok masih dalam peninjauan. Opsi ini diblokir oleh V-06.',
  'Supplier signal received': 'Sinyal pemasok diterima',
  'Sender verified': 'Pengirim terverifikasi',
  'Stock and demand compared': 'Stok dan permintaan dibandingkan',
  'Alternate supplier blocked': 'Pemasok alternatif diblokir',
  'Combined resolution proposed': 'Penyelesaian gabungan diusulkan',
  'Email and photo attached to the purchase order.': 'Email dan foto dilampirkan pada pesanan pembelian.',
  'Supplier identity matched against master data.': 'Identitas pemasok cocok dengan data induk.',
  'Source: SAP Mirror reference scenario.': 'Sumber: skenario acuan SAP Mirror.',
  'V-06 \u00b7 compliance status is UNDER_REVIEW.': 'V-06 \u00b7 status kepatuhan masih dalam peninjauan.',
  'Transfer first, then air freight. Human approval is required for air freight.': 'Transfer lebih dulu, lalu pengiriman udara. Pengiriman udara memerlukan persetujuan manusia.',
  'Synthetic demo \u00b7 no live writes': 'Demo sintetis \u00b7 tanpa penulisan nyata',
  'Understand the signal': 'Pahami sinyal', 'Set the priority': 'Tetapkan prioritas',
  'See what is at stake': 'Lihat dampaknya', 'Find a way forward': 'Cari jalan keluar',
  'Make the decision': 'Ambil keputusan', 'Track the outcome': 'Pantau hasilnya',
  'Reserve stock with an idempotency key': 'Cadangkan stok dengan kunci idempotensi',
  'Persist the undo plan': 'Simpan rencana pembatalan',
  'Create the stock transfer': 'Buat transfer stok',
  'Update purchase-order schedule': 'Perbarui jadwal pesanan pembelian',
  'Verify SAP results and notify': 'Periksa hasil SAP dan kirim pemberitahuan',
  'Monitor the goods receipt': 'Pantau penerimaan barang',
  'Use the demo role selector to explore it.': 'Gunakan pemilih peran demo untuk menjelajahinya.',
  'Demo setting updated locally. No backend workflow was changed.': 'Pengaturan demo diperbarui secara lokal. Alur kerja backend tidak berubah.',
  'Demo thresholds saved for this view only. Approval rules and backend configuration were not changed.': 'Ambang demo disimpan hanya untuk tampilan ini. Aturan persetujuan dan konfigurasi backend tidak berubah.',
  'Local demo settings restored.': 'Pengaturan demo lokal dipulihkan.',
  'No stock-out in 30 days.': 'Stok tidak habis dalam 30 hari.',
  'None in 30 days': 'Tidak ada dalam 30 hari',
  'Meridian planner': 'Perencana Meridian', 'Your workspace': 'Ruang kerja Anda',
  'Live updates connected': 'Pembaruan langsung terhubung',
  'Polling for updates': 'Memeriksa pembaruan berkala',
  'Reference scenario \u00b7 synthetic data': 'Skenario acuan \u00b7 data sintetis',
  'SAP-backed operations': 'Operasi berbasis data SAP',
  'The brake caliper case is ready for an approval review.': 'Kasus kaliper rem siap untuk ditinjau dan disetujui.',
  'You\u2019re up to date.': 'Semua sudah diperbarui.',
  'Reference day \u00b7 14 September': 'Hari acuan \u00b7 14 September',
  'Operations overview': 'Ringkasan operasi', 'Needs approval': 'Perlu persetujuan',
  'New signals': 'Sinyal baru',
  'Synthetic reference scenario': 'Skenario acuan sintetis',
  'Source-linked operational data': 'Data operasional dengan sumber',
  'All approvals': 'Semua persetujuan', 'Back to overview': 'Kembali ke ringkasan',
  'Ready for investigation': 'Siap diselidiki',
  'Case data connected': 'Data kasus terhubung',
  'This synthetic case illustrates the intake state. Open the brake caliper case for the complete reference workflow.': 'Kasus sintetis ini menunjukkan tahap penerimaan. Buka kasus kaliper rem untuk melihat alur acuan lengkap.',
  'Detailed signals, plan checks and execution data need the corresponding backend endpoints. No demo data is shown in this workspace.': 'Rincian sinyal, pemeriksaan rencana, dan data eksekusi memerlukan endpoint backend. Tidak ada data demo di ruang kerja ini.',
  'Confirmed by demo planner': 'Dikonfirmasi perencana demo',
  'Glare on the photo makes this quantity uncertain.': 'Pantulan cahaya pada foto membuat jumlah ini tidak pasti.',
  'Blocked \u00b7 V-06': 'Diblokir \u00b7 V-06', 'Proposed': 'Diusulkan',
  'Compliance not approved': 'Kepatuhan belum disetujui',
  'Source evidence available': 'Sumber bukti tersedia',
  'Reversible before goods issue': 'Dapat dibatalkan sebelum barang dikeluarkan',
  'Requires human approval': 'Memerlukan persetujuan manusia',
  'Approved locally \u00b7 awaiting live integration': 'Disetujui secara lokal \u00b7 menunggu integrasi aktif',
  'Execution is waiting for approval': 'Eksekusi menunggu persetujuan',
  'Live': 'Langsung', 'Polling': 'Pemeriksaan berkala',
  'Confirm demo approval': 'Konfirmasi persetujuan demo',
  'Reject demo plan': 'Tolak rencana demo',
  'Confirm approval': 'Konfirmasi persetujuan',
  'Confirm rejection': 'Konfirmasi penolakan',
  'Reason (required)': 'Alasan (wajib)', 'Comment (optional)': 'Komentar (opsional)',
  'Switch to the demo approver role to try an approval.': 'Beralih ke peran penyetuju demo untuk mencoba persetujuan.',
  'Approval actions require an authorised approver and connected approval endpoints.': 'Persetujuan memerlukan penyetuju berwenang dan endpoint yang terhubung.',
  'Demo advise-only mode is on.': 'Mode saran saja pada demo aktif.',
  'Execution still requires valid checks and the appropriate approval.': 'Eksekusi tetap memerlukan pemeriksaan sah dan persetujuan yang sesuai.',
  'Let\u2019s make this exception clearer. I can walk you through the reference scenario. These are demo explanations, not live model responses.': 'Mari perjelas pengecualian ini. Saya dapat menjelaskan skenario acuan. Ini penjelasan demo, bukan respons model aktif.',
  'Ask about this case or suggest constraints for a new plan.': 'Tanyakan kasus ini atau usulkan batasan untuk rencana baru.',
  'Chat cannot approve or execute a plan, change tiers, or bypass checks. Review the plan in Approvals using an authorised approver role.': 'Percakapan tidak dapat menyetujui atau menjalankan rencana, mengubah tingkat, atau melewati pemeriksaan. Tinjau rencana lewat Persetujuan dengan peran penyetuju berwenang.',
  'Your constraint would start a new plan in a connected workspace. This demo does not run a model or change the proposed plan.': 'Batasan Anda akan memulai rencana baru di ruang kerja terhubung. Demo ini tidak menjalankan model atau mengubah rencana usulan.',
  'In the reference scenario, the supplier is late. An inter-plant transfer bridges the immediate gap, followed by air freight for the ready partial shipment. Review Impact for the source figures and Options for costs. Air freight needs a named approver.': 'Dalam skenario acuan, pemasok terlambat. Transfer antar pabrik menutup kekurangan segera, diikuti pengiriman udara untuk barang sebagian yang siap. Lihat Dampak untuk angka bersumber dan Opsi untuk biaya. Pengiriman udara memerlukan penyetuju yang ditunjuk.',
  'Your question was submitted. Follow the case trace for the response.': 'Pertanyaan Anda dikirim. Ikuti jejak kasus untuk responsnya.',
  'Could not send your message.': 'Pesan tidak dapat dikirim.',
  'Demo guide': 'Panduan demo', 'Case conversation': 'Percakapan kasus',
  'Explain this case': 'Jelaskan kasus ini',
  'Why is approval needed?': 'Mengapa perlu persetujuan?',
  'Replan with a lower budget': 'Buat ulang rencana dengan anggaran lebih rendah',
  'Synthetic projection': 'Proyeksi sintetis', 'SAP-backed projection': 'Proyeksi berbasis SAP',
  'Pass': 'Lulus', 'Blocked': 'Diblokir',
  'received': 'diterima', 'triaged': 'ditriase', 'investigating': 'diselidiki',
  'waiting planner': 'menunggu perencana', 'waiting supplier': 'menunggu pemasok',
  'plan proposed': 'rencana diusulkan', 'awaiting approval': 'menunggu persetujuan',
  'approved': 'disetujui', 'rejected': 'ditolak', 'executing': 'dieksekusi',
  'monitoring': 'dipantau', 'closed': 'selesai', 'escalated': 'dieskalasi',
  'reopened': 'dibuka kembali',
  'Revenue protected': 'Pendapatan yang terlindungi',
  'Resolution median': 'Median waktu penyelesaian',
  'Resolution p95': 'Persentil ke-95 waktu penyelesaian',
  'Touchless rate': 'Tingkat penyelesaian otomatis',
  'Approvals requested': 'Persetujuan yang diminta',
  'Approvals avoided': 'Persetujuan yang tidak diperlukan',
  'Blocked signals': 'Sinyal yang diblokir',
  'Model cost per case': 'Biaya model per kasus',
  'Optimiser savings': 'Penghematan pengoptimal',
  'Measured on': 'Diukur dari',
  'reference scenario (synthetic SAP Mirror)': 'skenario acuan (SAP Mirror sintetis)',
  'Sample': 'Sampel',
  'Awaiting measured data': 'Menunggu data terukur',
  'Loading measured outcomes': 'Memuat hasil terukur',
  'Measured outcomes need live runs': 'Hasil terukur memerlukan uji langsung',
  'Demo data is synthetic. No resolution, cost or savings claim is shown here.': 'Data demo bersifat sintetis. Tidak ada klaim penyelesaian, biaya, atau penghematan di sini.',
  'SCENARIO LAB': 'LAB SKENARIO',
  'Synthetic Lab': 'Lab sintetis',
  'Choose a disruption. Watch AERA respond.': 'Pilih gangguan. Lihat respons AERA.',
  'Test a new disruption.': 'Uji gangguan baru.',
  'Open judge mode': 'Buka mode juri', 'Exit judge mode': 'Keluar dari mode juri',
  'Synthetic SAP Mirror scenario. Choose inputs; no outcome is scripted.': 'Skenario SAP Mirror sintetis. Pilih masukan; hasil tidak diatur sebelumnya.',
  '1 / Shape the exception': '1 / Atur pengecualian',
  '2 / Follow the outcome': '2 / Pantau hasil',
  'Material': 'Material',
  'Days late': 'Hari keterlambatan', 'Quantity short': 'Jumlah kekurangan',
  'Delivery channel': 'Saluran pengiriman', 'Language': 'Bahasa',
  'Email with PDF': 'Email dengan PDF', 'WhatsApp photo': 'Foto WhatsApp',
  'Carrier event': 'Peristiwa pengangkut',
  'Include a hostile message': 'Sertakan pesan berbahaya',
  'Starting...': 'Memulai...', 'Preview synthetic inputs': 'Pratinjau masukan sintetis',
  'Run this disruption': 'Jalankan gangguan ini',
  'Preview only. No Mirror mutation or signal delivery.': 'Hanya pratinjau. Tidak ada perubahan Mirror atau pengiriman sinyal.',
  'Signal delivery mode appears with each run. Provider traffic needs live setup.': 'Mode pengiriman sinyal tampil pada setiap proses. Lalu lintas penyedia memerlukan pengaturan langsung.',
  'Gate accepted hostile message': 'Gerbang menerima pesan berbahaya',
  'Synthetic preview': 'Pratinjau sintetis', 'Ready to test': 'Siap diuji',
  'days late': 'hari terlambat', 'units short': 'unit kurang',
  'Connected mode will mutate the Mirror and submit a gated signal.': 'Mode terhubung akan mengubah Mirror dan mengirim sinyal melalui gerbang.',
  'Awaiting your selection': 'Menunggu pilihan Anda',
  'Real parameters. Open outcome.': 'Parameter nyata. Hasil terbuka.',
  'Case progress, hostile-message result and audit timing appear here.': 'Kemajuan kasus, hasil pesan berbahaya, dan waktu audit tampil di sini.',
  'Run status unavailable. Retry from run history.': 'Status uji tidak tersedia. Coba lagi dari riwayat uji.',
  'Previous synthetic runs': 'Uji sintetis sebelumnya',
  'Loading runs...': 'Memuat uji...', 'No Lab runs yet.': 'Belum ada uji Lab.',
  'Synthetic run': 'Uji sintetis',
  'Hostile message': 'Pesan berbahaya', 'Blocked by gate': 'Diblokir gerbang',
  'Awaiting gate result': 'Menunggu hasil gerbang',
  'Time to verified plan': 'Waktu hingga rencana terverifikasi',
  'The Scenario Lab is available to the admin role.': 'Lab Skenario tersedia bagi peran admin.',
  'reference scenario and Lab runs (synthetic SAP Mirror)': 'skenario acuan dan uji Lab (SAP Mirror sintetis)',
};
